# Generated by Django 4.1.5 on 2023-01-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_uplaodfile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='uplaodfile',
            name='datentime',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-30 10:50:12'),
            preserve_default=False,
        ),
    ]
