# Generated by Django 4.1.5 on 2023-01-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_uplaodfile_datentime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uplaodfile',
            name='adhar',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='uplaodfile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='uplaodfile',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
