# Generated by Django 4.1.5 on 2023-01-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_uplaodfile_adhar_alter_uplaodfile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uplaodfile',
            name='adhar',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='uplaodfile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='uplaodfile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
